adminzone/urls.py
from django.urls import re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'adminzone'

urlpatterns = [
    re_path(r'^$', views.index, name = 'admin_index'),
    re_path(r'^treatment', views.treatment, name = 'admin_treatment'),
    re_path(r'^about', views.about, name = 'admin_about'),
    re_path(r'^project', views.project, name = 'admin_project'),
    re_path(r'^signout', views.signout, name = 'admin_signout'),
    re_path(r'^predict', views.predict, name = 'predict')
]

generalzone/urls.py
from django.urls import re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'generalzone'

urlpatterns = [
    re_path(r'^$', views.index, name = 'index'),
    re_path(r'^treatment', views.treatment, name = 'treatment'),
    re_path(r'^about', views.about, name = 'about'),
    re_path(r'^project', views.project, name = 'project'),
    re_path(r'^login', views.login, name = 'login'),
    re_path(r'^validate', views.validate, name = 'validate'),
    re_path(r'^signup', views.signup, name = 'signup'),
    re_path(r'^createUser', views.createUser, name = 'createUser')
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myproject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from generalzone.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_required(home), name='home'),
    path('generalzone/', include('generalzone.urls')),
    path('adminzone/', include('adminzone.urls')),
 ]
          

adminzone/models.py
from django.db import models

# Create your models here.
from django.db import models

class MyModel(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

generalzone/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    name = models.CharField(max_length = 50)
    email = models.EmailField()
    contact = models.CharField(max_length = 15)
    password = models.CharField(max_length = 20)
    image = models.CharField(max_length = 100)

adminzone/views.py
from django.shortcuts import render, redirect, reverse
from generalzone.models import User
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponse
# from keras.layers import TFSMLayer
from keras.models import load_model

import cv2 
import tensorflow as tf
from tensorflow.keras.preprocessing.image import array_to_img, img_to_array, load_img 
import numpy as np # linear algebra 
# Create your views here.
def index(req):
    try:
        img = load_img('./abc.jpg')
        img = img_to_array(img)
        img = cv2.resize(img, (128,128)) 
        img = np.array(img, dtype="float") / 255.0 
        img = np.expand_dims(img, axis = 0) 
        # pred = model.predict(img) 
        # y_pred= np.argmax(pred, axis = 1) 
        # print(y_pred[0]) 
        print(req.session['userid'])
        if req.session['userid']:
            return render(req,'admin_index.html')
    except KeyError:
        pass
    return redirect(reverse('generalzone:index'))

def about(req):
    try:
        print(req.session['userid'])
        if req.session['userid']:
            return render(req,'admin_about.html')
    except KeyError:
        pass
    return redirect(reverse('generalzone:index'))

def treatment(req):
    try:
        if req.session['userid']:
            return render(req,'admin_treatment.html')
    except KeyError:
        pass
    return redirect(reverse('generalzone:index'))

def project(req):
    try:
        if req.session['userid']:
            return render(req,'admin_project.html')
    except KeyError:
        pass
    return redirect(reverse('generalzone:index'))

def signout(req):
    try:
        if req.session['userid']:
            del req.session['userid']
    except KeyError:
        pass
    return redirect(reverse('generalzone:index'))

def int_to_classes(i):
    if i == 0: return "No Diabetic Retinopathy"
    elif i == 1: return "Mild Diabetic Retinopathy"
    elif i == 2: return "Moderate Diabetic Retinopathy"
    elif i == 3: return "Severe Diabetic Retinopathy"
    elif i == 4: return "Proliferative Diabetic Retinopathy"
    print("Invalid class ", i)
    return "Invalid Class"

def predict(req):
    File = req.FILES["image"]      
    image=File.name
    fs=FileSystemStorage()
    img = fs.save(image,File)
    img = load_img(img)
    img = img_to_array(img)
    img = cv2.resize(img, (600,600)) 
    img = np.array(img, dtype="float") / 255.0    
    img = np.expand_dims(img, axis = 0)    
    model = load_model("MY_MODEL/mymodel.keras") 
    # model = tf.saved_model.load("MY_MODEL/mymodel")
    pred = model.predict(img)     
    y_pred= np.argmax(pred, axis = 1)           
    print(y_pred[0]) 
    html = "<html><body>It is now Awsome</body></html>"
    return render(req, 'admin_predictOutput.html', {'output': int_to_classes(y_pred[0])})

generalzone/views.py
from django.shortcuts import render, redirect, reverse
from django.core.files.storage import FileSystemStorage
from .models import User
from django.core.exceptions import ObjectDoesNotExist
# from keras.models import load_model 
# import cv2 
# from tensorflow.keras.preprocessing.image import array_to_img, img_to_array, load_img 
# import numpy as np # linear algebra 

# Create your views here.
def home(req):
    # img = load
    return render(req, 'home.html')

def index(req):
    # img = load
    return render(req, 'index.html')

def treatment(req):
    return render(req, 'treatment.html')

def about(req):
    return render(req, 'about.html')

def project(req):
    return render(req, 'project.html')

def login(req):
    return render(req, 'login.html')

def validate(req):
    email = req.POST["email"]
    password = req.POST["password"]
    try:
        v = User.objects.get(email = email,password = password)
        if v is not None:
            req.session['userid']= v.id
            return redirect(reverse('adminzone:admin_index'))
    except ObjectDoesNotExist or ValueError:
        pass
    return redirect('generalzone:index')
    
def createUser(req):
    email = req.POST["email"]
    name = req.POST["name"]
    password = req.POST["password"]
    contact = req.POST["contact"]
    File = req.FILES["image"]
    if User.objects.filter(email = email).exists():
        return render(req, 'index.html')
    image=File.name
    fs=FileSystemStorage()
    fs.save(image,File)
    c = User(name = name, contact = contact, email = email, password = password, image = image)
    c.save()
    return render(req, 'index.html')

def signup(req):
    return render(req, 'signup.html')
    

adminzone/templates/admin_about.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href='https://fonts.googleapis.com/css?family=Rubik' rel='stylesheet'>
	<title>Diabetic Retinopathy</title>
	<style>
		*{
			margin: 0;
		}
		body{
			/*background: linear-gradient(to top right, #6600ff 0%, #ff99cc 100%);*/
			height: fit-content;
			font-family: 'Rubik';
			border: 1px solid transparent; box-sizing: border-box;
		}
		.header{
			height: 50px;
			width: 100%;
			line-height: 50px;
			padding: 0 10%;
			box-sizing: border-box;
			font-size: 30px;
			font-weight: bolder;
			position: fixed;
			/*background-color: purple;*/
			/*box-shadow: 1px 1px purple;*/
			/*box-shadow: 20px 20px 50px 10px pink inset;*/
			box-shadow: 1px 1px 20px 1px #ff99cc;
			background-color: white;
			z-index: 10;
		}
		ul{
			list-style-type: none;
			width: fit-content;
			float: right;
			/*margin-right: 50px;*/
		}
		li{
			font-size: 20px;
			display: inline-block;
			width: fit-content;
			margin-left: 20px;
		}
		li a{
			text-decoration: none;
			color: black;
		}
		.body{
			/*height: fit-content;*/
			height: fit-content;
			width: 80%;
			margin: 0px auto;
			margin-top: 80px;
			background-color: whitesmoke;
			box-shadow: 1px 1px 20px 1px #00000033;
			position: relative;
			font-size: 20px;
			padding: 5%;
			box-sizing: border-box;
		}
	</style>
</head>
<body>
	<!-- <div class="header"></div> -->
	<div class="header">
		Diabetic Retinopathy
		<ul>
			<li><a href="{% url 'adminzone:admin_index' %}">Home</a></li>
			<li><a href="{% url 'adminzone:admin_about' %}">About</a></li>
			<li><a href="{% url 'adminzone:admin_treatment' %}">Treatment</a></li>
			<li><a href="{% url 'adminzone:admin_project' %}">Project</a></li>
			<li><a href="{% url 'adminzone:admin_signout' %}">Logout</a></li>
		</ul>
	</div>
	<div class="body">
		<h2>What is diabetic retinopathy ?</h2>
		<br>
		Diabetic retinopathy is an eye condition that can cause vision loss and blindness in people who have diabetes. It affects blood vessels in the retina (the light-sensitive layer of tissue in the back of your eye).
		<br><br>
		If you have diabetes, it’s important to get a comprehensive dilated eye exam at least once a year. Diabetic retinopathy may not have any symptoms at first — but finding it early can help you take steps to protect your vision. 
		<br><br>
		Managing your diabetes — by staying physically active, eating healthy, and taking your medicine — can also help you prevent or delay vision loss.  
	</div>
</body>
</html>

adminzone/templates/admin_project.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href='https://fonts.googleapis.com/css?family=Rubik' rel='stylesheet'>
	<title>Diabetic Retinopathy</title>
	<style>
		*{
			margin: 0;
		}
		body{
			/*background: linear-gradient(to top right, #6600ff 0%, #ff99cc 100%);*/
			height: fit-content;
			font-family: 'Rubik';
			border: 1px solid transparent; box-sizing: border-box;
		}
		.header{
			height: 50px;
			width: 100%;
			line-height: 50px;
			padding: 0 10%;
			box-sizing: border-box;
			font-size: 30px;
			font-weight: bolder;
			position: fixed;
			/*background-color: purple;*/
			/*box-shadow: 1px 1px purple;*/
			/*box-shadow: 20px 20px 50px 10px pink inset;*/
			box-shadow: 1px 1px 20px 1px #ff99cc;
			background-color: white;
			z-index: 10;
		}
		ul{
			list-style-type: none;
			width: fit-content;
			float: right;
			/*margin-right: 50px;*/
		}
		li{
			font-size: 20px;
			display: inline-block;
			width: fit-content;
			margin-left: 20px;
		}
		li a{
			text-decoration: none;
			color: black;
		}
		.body{
			/*height: fit-content;*/
			height: fit-content;
			width: 80%;
			margin: 0px auto;
			margin-top: 80px;
			background-color: whitesmoke;
			box-shadow: 1px 1px 20px 1px #00000033;
			position: relative;
			font-size: 20px;
			padding: 5%;
			box-sizing: border-box;
		}
		.btn{
			background-color: #3fc;
			border-radius: 20px;
			width: 150px;
			height: 35px;
			margin: 0 auto;
			text-align: center;
			border: none;
			cursor: pointer;
			font-size: 20px;
			/* box-sizing: content-box; */
			display: block;
			/* margin: 10px auto; */
		}
		label {
			background: linear-gradient(to top right, #6600ff 0%, #ff99cc 100%);
			color: white;
			padding: 0.5rem;
			font-family: sans-serif;
			border-radius: 0.3rem;
			cursor: pointer;
			margin-top: 1rem;
			font-size: 18px;
			border-radius: 25px;
		}
	</style>
</head>
<body>
	<!-- <div class="header"></div> -->
	<div class="header">
		Diabetic Retinopathy
		<ul>
			<ul>
				<li><a href="{% url 'adminzone:admin_index' %}">Home</a></li>
				<li><a href="{% url 'adminzone:admin_about' %}">About</a></li>
				<li><a href="{% url 'adminzone:admin_treatment' %}">Treatment</a></li>
				<li><a href="{% url 'adminzone:admin_project' %}">Project</a></li>
				<li><a href="{% url 'adminzone:admin_signout' %}">Logout</a></li>
			</ul>
		</ul>
	</div>
	<div class="body">
		<h3 style="text-align: center;">Upload image to get the result</h3>
		<br>
		<form action="{% url 'adminzone:predict' %}" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<input type="file" id="actual-btn" name="image" hidden/>

			<!-- our custom upload button -->
			<label for="actual-btn">Choose File</label>

			<!-- name of file chosen -->
			<span id="file-chosen">No file chosen</span>
		<br>
		<br>
		<br>
		<input type="submit" value="Submit" class="btn">
		</form>
	</div>
	<script>
		const actualBtn = document.getElementById('actual-btn');

		const fileChosen = document.getElementById('file-chosen');

		actualBtn.addEventListener('change', function(){
			fileChosen.textContent = this.files[0].name;
		})
	</script>
</body>
</html>

generalzone/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome</title>
    <style>
    .button {
        display: inline-block; /* Make it behave like a button */
        padding: 10px 20px; /* Add padding for the button's size */
        background-color: #007bff; /* Button background color */
        color: white; /* Button text color */
        text-align: center; /* Center the text inside the button */
        text-decoration: none; /* Remove the underline from the link */
        border-radius: 5px; /* Rounded corners */
        font-size: 16px; /* Text size */
        transition: background-color 0.3s; /* Smooth transition for hover effect */
    }
    
    .button:hover {
        background-color: #0056b3; /* Darker background color on hover */
    }
    </style>
</head>
<body>
   <div>
    <h1>Welcome to Our Project</h1>
    <h2>By Ayush Kumar <br> & Ishita Pandey</h2>
    <a href="{% url 'generalzone:index' %}" class="button">Open Project</a>
   </div> 
</body>
</html>

generalzone/templates/login.html
<!DOCTYPE html>
<html>
	{% load static %}
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href='https://fonts.googleapis.com/css?family=Rubik' rel='stylesheet'>
	<title>Diabetic Retinopathy</title>
	<style>
		*{
			margin: 0;
		}
		body{
			/*background: linear-gradient(to top right, #6600ff 0%, #ff99cc 100%);*/
			height: fit-content;
			font-family: 'Rubik';
			border: 1px solid transparent; box-sizing: border-box;
		}
		.header{
			height: 50px;
			width: 100%;
			line-height: 50px;
			padding: 0 10%;
			box-sizing: border-box;
			font-size: 30px;
			font-weight: bolder;
			position: fixed;
			/*background-color: purple;*/
			/*box-shadow: 1px 1px purple;*/
			/*box-shadow: 20px 20px 50px 10px pink inset;*/
			box-shadow: 1px 1px 20px 1px #ff99cc;
			background-color: white;
			z-index: 10;
		}
		ul{
			list-style-type: none;
			width: fit-content;
			float: right;
			/*margin-right: 50px;*/
		}
		li{
			font-size: 20px;
			display: inline-block;
			width: fit-content;
			margin-left: 20px;
		}
		li a{
			text-decoration: none;
			color: black;
		}
		.body{
			/*height: fit-content;*/
			height: fit-content;
			width: 80%;
			margin: 0px auto;
			margin-top: 80px;
			/* background-color: whitesmoke; */
			box-shadow: 1px 1px 20px 1px #00000033;
			position: relative;
			font-size: 20px;
			padding: 5%;
			box-sizing: border-box;
		}
        .section-1{
            width: 80%;
            height: 300px;
            /* background-color: #ff99cc; */
            margin: 0px auto;
        }
        .col{
            width: 50%;
            /* background-color: aqua; */
            height: 100%;
            float: left;
            text-align: center;
            line-height: 40px;
        }
        .active{
            background-color: aqua;
			color: white;
            border-radius: 25px;
            width: 90%;
            margin: 0 auto;
            height: 40px;
            background: linear-gradient(to top right, #6600ff 0%, #ff99cc 100%);
        }
        .form-container{
				height: fit-content;
				width: 100%;
				margin: 0px auto;
				/* border: 1px solid; */
				/* padding: 5%; */
				/* padding-left: 0; */
				box-sizing: border-box;
				/* background-color: yellow; */
			}
			.input-field{
				position: relative;
				padding: 0;
				height: 30px;
				width: 90%;
				margin-left: 5%;
                /* margin: 0 auto; */
				box-sizing: border-box;
			}
			.input-field{
                margin: 0 auto;
				margin-top: 50px;
				
			}
			input, textarea, select{
				outline: none;
				border: none;
				width: 100%;
				height: 100%;
				border-bottom: 1px solid #3fc;
				position: relative;
				
				margin-left: 0;
				font-size: 18px;
				
			}
			
			input:focus{
				border-bottom: 2px solid #3fc;
			}
			label{
				position: absolute;
				/* width: 100%; */
				/* height: 100%; */
				left: 0;
				top: 0;
				transition: all 0.3s;
				/* background-color: yellowgreen; */
			}
			input:focus ~ label,
			.input-has-val ~ label,
			textarea:focus ~ label,
			select:focus ~ label{
				left: 0;
				font-size: 12px;
				top: -20px;
			}
			.btn{
				background-color: #3fc;
				border-radius: 20px;
				width: 150px;
                height: 35px;
                margin: 0 auto;
				text-align: center;
				cursor: pointer;
				/* box-sizing: content-box; */
				display: block;
				/* margin: 10px auto; */
			}
	</style>
</head>
<body>
	<!-- <div class="header"></div> -->
	<div class="header">
		Diabetic Retinopathy
		<ul>
			<li><a href="{% url 'generalzone:index' %}">Home</a></li>
			<li><a href="{% url 'generalzone:about' %}">About</a></li>
			<li><a href="{% url 'generalzone:treatment' %}">Treatment</a></li>
			<li><a href="{% url 'generalzone:project' %}">Project</a></li>
			<li><a href="{% url 'generalzone:login' %}">Login</a></li>
		</ul>
	</div>
	<div class="body">
        <!-- <div class="row" style="height: 40px;">
            <div class="col active">Login</div>
        </div> -->
        <div class="section-1">
            <div class="col">
                <div class="active">Login</div>
                <div class="form-container">
                    <form action="{% url 'generalzone:validate' %}" method="POST">
						{% csrf_token %}
                        <div class="input-field">
                            <input id="email" type="email" class="validate" name="email" autocomplete="off" style="padding-left: 4rem;" >
                            <label for="email">Email</label>
                        </div>
                        <div class="input-field">
                            <input id="password" type="password" class="validate" name="password" autocomplete="off" style="padding-left: 6rem;">
                            <label for="password">Password</label>
                        </div>
                        <div class="input-field">	
                            <input type="submit" value="Submit" class="btn">
                        </div>
                        Don't have account ? Create <a href="{% url 'generalzone:signup' %}">here</a>
                    </form>
                </div>
            </div>
            <div class="col" style="position: relative;">
				<img src="{% static '/images/download.jpg' %}" alt="" style="max-width: 100%; max-height: 100%; position: absolute; left: 0; right: 0; top: 0; bottom: 0; margin: auto;">
			</div>
        </div>
        <!-- <div class="row" style="height: 40px;">
            <div class="col">
                <div class="form-container">
                    <form action="">
                        <div class="input-field">
                            <input id="email" type="email" class="validate">
                            <label for="email">Email</label>
                        </div>
                        <div class="input-field">
                            <input id="password" type="password" class="validate">
                            <label for="password">Password</label>
                        </div>
                        <div class="input-field">	
                            <input type="submit" value="Submit" class="btn">
                        </div>
                    </form>
                </div>
            </div>
        </div> -->
        
	</div>
	<script>
		const inp = document.querySelectorAll('.validate');
		inp.forEach(item => {
			item.addEventListener('change', ()=>{
				if(item.value != ''){
					item.classList.add('input-has-val');
				}else{
					item.classList.remove('input-has-val');
				}
			})
		});
	</script>
</body>
</html>

generalzone/templates/signup.html
<!DOCTYPE html>
<html>
	{% load static %}
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href='https://fonts.googleapis.com/css?family=Rubik' rel='stylesheet'>
	<title>Diabetic Retinopathy</title>
	<style>
		*{
			margin: 0;
		}
		body{
			/*background: linear-gradient(to top right, #6600ff 0%, #ff99cc 100%);*/
			height: fit-content;
			font-family: 'Rubik';
			border: 1px solid transparent; box-sizing: border-box;
			padding-bottom: 50px;
		}
		.header{
			height: 50px;
			width: 100%;
			line-height: 50px;
			padding: 0 10%;
			box-sizing: border-box;
			font-size: 30px;
			font-weight: bolder;
			position: fixed;
			/*background-color: purple;*/
			/*box-shadow: 1px 1px purple;*/
			/*box-shadow: 20px 20px 50px 10px pink inset;*/
			box-shadow: 1px 1px 20px 1px #ff99cc;
			background-color: white;
			z-index: 10;
		}
		ul{
			list-style-type: none;
			width: fit-content;
			float: right;
			/*margin-right: 50px;*/
		}
		li{
			font-size: 20px;
			display: inline-block;
			width: fit-content;
			margin-left: 20px;
		}
		li a{
			text-decoration: none;
			color: black;
		}
		.body{
			/*height: fit-content;*/
			height: fit-content;
			width: 80%;
			margin: 0px auto;
			margin-top: 80px;
			/* background-color: whitesmoke; */
			box-shadow: 1px 1px 20px 1px #00000033;
			position: relative;
			font-size: 20px;
			padding: 5%;
			box-sizing: border-box;
		}
        .section-1{
            width: 80%;
            height: 480px;
            /* background-color: #ff99cc; */
            margin: 0px auto;
        }
        .col{
            width: 50%;
            /* background-color: aqua; */
            height: 100%;
            float: left;
            text-align: center;
            line-height: 40px;
        }
        .active{
            background-color: aqua;
			color: white;
            border-radius: 25px;
            width: 90%;
            margin: 0 auto;
            height: 40px;
            background: linear-gradient(to top right, #6600ff 0%, #ff99cc 100%);
        }
        .form-container{
				height: fit-content;
				width: 100%;
				margin: 0px auto;
				/* border: 1px solid; */
				/* padding: 5%; */
				/* padding-left: 0; */
				box-sizing: border-box;
				/* background-color: yellow; */
			}
			.input-field{
				position: relative;
				padding: 0;
				height: 30px;
				width: 90%;
				margin-left: 5%;
                /* margin: 0 auto; */
				box-sizing: border-box;
			}
			.input-field{
                margin: 0 auto;
				margin-top: 50px;
			}
			input, textarea, select{
				outline: none;
				border: none;
				width: 100%;
				height: 100%;
				border-bottom: 1px solid #3fc;
				position: relative;
				padding-left: 0;
				margin-left: 0;
				font-size: 18px;
			}
			input:focus{
				border-bottom: 2px solid #3fc;
			}
			label{
				position: absolute;
				/* width: 100%; */
				/* height: 100%; */
				left: 0;
				top: 0;
				transition: all 0.3s;
				/* background-color: yellowgreen; */
			}
			input:focus ~ label,
			.input-has-val ~ label,
			textarea:focus ~ label,
			select:focus ~ label{
				left: 0;
				font-size: 12px;
				top: -20px;
			}
			.btn{
				background-color: #3fc;
				border-radius: 20px;
				width: 150px;
                height: 35px;
                margin: 0 auto;
				text-align: center;
				cursor: pointer;
				/* box-sizing: content-box; */
				display: block;
				/* margin: 10px auto; */
			}
			#img-label {
				background: linear-gradient(to top right, #6600ff 0%, #ff99cc 100%);
				color: white;
				padding: 0.2rem;
				/* font-family: sans-serif; */
				border-radius: 0.3rem;
				cursor: pointer;
				/* margin-top: 1rem; */
				font-size: 18px;
				border-radius: 25px;
				height: 100%;
				/* box-sizing: border-box; */
				line-height: 30px;
			}
			#file-chosen{
				height: 100%;
				line-height: 30px;
				margin-top: 0;
			}
	</style>
</head>
<body>
	<!-- <div class="header"></div> -->
	<div class="header">
		Diabetic Retinopathy
		<ul>
			<li><a href="{% url 'generalzone:index' %}">Home</a></li>
			<li><a href="{% url 'generalzone:about' %}">About</a></li>
			<li><a href="{% url 'generalzone:treatment' %}">Treatment</a></li>
			<li><a href="{% url 'generalzone:project' %}">Project</a></li>
			<li><a href="{% url 'generalzone:login' %}">Login</a></li>
		</ul>
	</div>
	<div class="body">
        <!-- <div class="row" style="height: 40px;">
            <div class="col active">Login</div>
        </div> -->
        <div class="section-1">
            <div class="col">
                <div class="active">Login</div>
                <div class="form-container">
                    <form action="{% url 'generalzone:createUser' %}" method="POST" enctype="multipart/form-data">
						{% csrf_token %}
                        <div class="input-field">
                            <input id="name" type="name" class="validate" name="name">
                            <label for="name">Name</label>
                        </div>
						<div class="input-field">
                            <input id="contact" type="tel" class="validate" name="contact">
                            <label for="contact">Contact</label>
                        </div>
                        <div class="input-field">
                            <input id="email" type="email" class="validate" name="email" autocomplete="off" style="padding-left: 4rem;">
                            <label for="email">Email</label>
                        </div>
                        <div class="input-field">
                            <input id="password" type="password" class="validate" name="password" autocomplete="off" style="padding-left: 6rem;">
                            <label for="password">Password</label>
                        </div>
						<div class="input-field">
                            <input type="file" id="actual-btn" name="image" hidden/>

							<!-- our custom upload button -->
							<label for="actual-btn" id='img-label'>Choose File</label>
					
							<!-- name of file chosen -->
							<span id="file-chosen">No file chosen</span>
                        </div>
                        <div class="input-field">	
                            <input type="submit" value="Submit" class="btn">
                        </div>
                    </form>
                </div>
            </div>
            <div class="col" style="position: relative;">
				<img src="{% static '/images/download.jpg' %}" alt="" style="max-width: 100%; max-height: 100%; position: absolute; left: 0; right: 0; top: 0; bottom: 0; margin: auto;">
			</div>
        </div>
        
	</div>
	<script>
		
		const inp = document.querySelectorAll('.validate');
		inp.forEach(item => {
			item.addEventListener('change', ()=>{
				if(item.value != ''){
					item.classList.add('input-has-val');
				}else{
					item.classList.remove('input-has-val');
				}
			})
		});
		const actualBtn = document.getElementById('actual-btn');

		const fileChosen = document.getElementById('file-chosen');

		actualBtn.addEventListener('change', function(){
			fileChosen.textContent = this.files[0].name;
		})
	</script>
</body>
</html>